SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2


#Player Constants#
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_STATUS_NORM = 1
PLAYER_STATUS_POWER_UP = 2
PLAYER_STATUS_POWER_MAX = 3

#Asteroid Constants#
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
SMALL_ASTEROID_COLOR = "red"
MED_ASTEROID_COLOR = "orange"
LARGE_ASTEROID_COLOR = "yellow"

#Shooting Constants# 
SHOT_RADIUS = 2
SHOT_POWERUP_NORMAL = 2
SHOT_POWERUP_MAX = 4
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3


#Health Constants#
SHOT_STRENGTH = 1
ASTEROID_MIN_HEALTH = 3
ASTEROID_MAX_HEALTH = ASTEROID_MIN_HEALTH * ASTEROID_KINDS
PLAYER_FULL_HEALTH = 100
PLAYER_SHIELD_HEALTH = 50
ASTEROID_MIN_DAMAGE = .25
